# Specify the base image
FROM node:alpine

# Specify working directory
WORKDIR '/app'

# COPY package json
COPY package.json ./

# install dependencies
RUN npm install

# Copy source files
COPY ./ ./

# Specify Default command
CMD ["npm", "run", "start"]

# <port shown on startup> is 3000 in create-react-app
# to run docker run -p 3000: 3000 containerID