# Only used to configure https in production setup.
# We are using https://letsencrypt.org/ for certificate.
# We are giving this apiVersion as this is not a object
# defined by k8s. But by certmanager. So we need to give this
# apiVersion so that we can reach cert manager defined bucket of
# objects and then create one of type issuer.
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  # telling we need to reach out to letsencrypt prod version
  name: letsencrypt-prod
spec:
  acme:
    # url of letsencrypt api which is used to setup all communication link
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "oberoiishant@yahoo.com" # not used yet as per requirement from letsencrypt.
    privateKeySecretRef:
      name: letsencrypt-prod # a key tied to our recored in letsencrypt. Not related to the certificate secret. It helps in communication with letsencrypt for certificate.
    solvers:
      # we want to use http to react out to letsencrypt for certificate. Other option is DNS.
      - http01:
          ingress:
            class: nginx


